CREATE TABLE CONTACT (
ID INT NOT NULL AUTO_INCREMENT
, FIRST_NAME VARCHAR(60) NOT NULL
, LAST_NAМE VARCHAR(40) NOT NULL
, BIRTH_DATE DATE
, UNIQUE CONTACT_1(FIRST_NAME, LAST_NAME)
  PRIMARY KEY (ID)
);

CREATE ТАВLЕ CONTACT TEL_DETAIL (
ID INT NOT NOLL АОТО INCREMENT
, CONTACT_ID INT NOT NOLL
, TEL_TYPE VARCНAR(20) NOT NOLL
, TEL_NOМBER VARCНAR(20) NOT NOLL
, ONIQOE OQ_CONTACT_TEL_DETAIL_l (CONTACT_ID, TEL_TYPE)
, PRIМARY КЕУ (ID)
, CONSTRAINT FK_CONTACT_TEL_DETAIL_l FOREIGN КЕУ (CONTACT_ID)CONTACT
FIRSТ_NAME VARCHAR(60)
lAST_NAME VARCHAR(40) BIRTH_DATE DATE
CONTACT_TEL_DEТAIL
);